### ISSUE TITLE
There will be garbled code when Chinese is used in the notification

### ISSUE THREAD

**Issue by holai** [alexmercerind/desktoasts#1]
![企业微信截图_16207216135033](https://user-images.githubusercontent.com/36557839/117784347-0e41a400-b276-11eb-94c9-9fe32a35d7a8.png)

**Comment by alexmercerind** [comment]
Thanks for the report.

**Comment by alexmercerind** [comment]
@holai 
How does this look? I'll push in a while.
![desktoasts](https://user-images.githubusercontent.com/28951144/117805769-00405300-b277-11eb-8fbc-bf6dbcf0c1f0.PNG)

**Comment by holai** [comment]
> @holai看起来
> 如何？我会推一会儿。
> ![敬酒](https://user-images.githubusercontent.com/28951144/117805769-00405300-b277-11eb-8fbc-bf6dbcf0c1f0.PNG)

Great. Just what I wanted

**Comment by alexmercerind** [comment]
Ok, go get 0.0.2.
